version: '3.9'

services: 
  web:
    command: python3 app.py
    image: mrwhitecat/car_price_predict:v0.1
    build:
      context: .
      dockerfile: .Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORTS=8080
    ports:
      - "8080:8080"